### ISSUE TITLE
Version number and settings issues with release 1.1.1

### ISSUE THREAD

**Issue by iamfin3** [albinaask/Log#5]
1. The new version released a couple days ago as 1.1.1 still has 1.1.0 in the plugin config file. 
1. If you don't go in to the settings and set the new UTC preference, you get an error message indicating the setting is `null`. Once you check/uncheck the box and save settings, it works fine.
1. If you don't go into Settings and add a character to the `Log Message Format` key, close out of Settings and then go back in and remove that character, that setting is also `null` and an error is received (error comes from line 119 in log-stream.gd).

These are all from a clean/blank install not an update. Unsure if those who upgrade from 1.1.0 to 1.1.1 will have these issues.

**Comment by albinaask** [comment]
Thankyou for reporting the bugs. Use the 1.0 version until I can fix it. The only difference is that the settings aren't yet in the editor settings tab, but instead constants in the code which you can change to your heart's desire. This update should have none of the settings described. You can download it from here if you select the button "code" from the "code" tab and selecting "1.0.0" under tags, that is available if you click on the branch select button to the top left of the file selector.

**Comment by iamfin3** [comment]
Oh, I got 1.1.1 to work - the workaround is listed for 2 and 3 above. Once you toggle the settings in the editor manually, everything seems to work (I think). It's just a little bit of initialization issues it seems (the values are null until you change them and save in the editor for some reason; Maybe it's a godot thing.) You might put that in the readme if it's gonna be a bit before it gets fixed.

**Comment by albinaask** [comment]
As long as it is working that's good! I'll get on fixing it!
