### ISSUE TITLE
Disable printing the tree when writing an error

### ISSUE THREAD

**Issue by Lyaaaaaaaaaaaaaaa** [albinaask/Log#8]
Hi, is it possible to disable printing the tree?

**Why ?**
Every time I use the error function, it prints the whole tree. While it might be useful in specific cases, having it by default is terrible (at least for my use case).

I find myself with 3k of lines displaying my tree for every error. So, 2999 lines are useless while one is relevant.

**How to do it?**
I didn't find anything about this. Did I miss an option or something?
Otherwise, I would ask as a feature request the possibility to disable this behavior ;).

In the meantime, I commented the line displaying it.

**Comment by albinaask** [comment]
Thank you for the input. You get really blind to what other users need when you write these kinds of plugins, so input is honestly GREATLY appreciated!I share your opinion that this should be an option to toggle that is disabled by default. Nice that you've found a workaround for now, but the next version of Log will definitely include this option.
